### ISSUE TITLE
Figure out a way to make foundry/forge be lighter weight

### ISSUE THREAD

**Issue by zombieprocess** [zombieprocess/foundryvtt-dnd5e-config#13]
Does Foundry download the entire world on each person's computer, or does it only load the stuff that is needed right there and then????

https://forums.forge-vtt.com/docs?search=world%20size&topic=12105

![](https://cdn.discordapp.com/attachments/795752893704962068/1031237631104798780/Screenshot_2022-10-16_at_11.09.24_AM.png)

**Comment by zombieprocess** [comment]
What is the storage quota in ForgeVTT? 

It makes me wonder if this is a forge issue and not a foundry issue...

**Comment by zombieprocess** [comment]
![](https://cdn.discordapp.com/attachments/795752893704962068/1031607264332759090/Screenshot_2022-10-17_at_11.38.38_AM.png)


![](https://cdn.discordapp.com/attachments/795752893704962068/1031607555639742484/Screenshot_2022-10-17_at_11.39.50_AM.png)

@zimmer777 👀 

#### Adding notes here:
- Foundry/Forge definition of **World** is all the `*.db` files
- can clear `fog.db` anytime
- can clear `messages.db` between areas/chapters, keep 2 sessions of chats is reasonable
- need to create a filter for monster imports (don't import all) - this is the biggest DB

**Comment by zombieprocess** [comment]
New test server was built with a clean import from DnD Beyond and the total size is 90 MB. (vs 172 MB)

Did not get the warning that the world size is too large (aka DB sizes are too big) from the Forge module.

**Comment by zombieprocess** [comment]
@zimmer777 What do you think, is this issue resolved for now?

Solution being make a new "trimmed" server.

**Comment by zimmer777** [comment]
Let's close this as an issue for now and add one as part of the future v10 migration to make sure to add only a filtered list of monsters.
